# Generated by Django 4.0.5 on 2022-07-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=64, verbose_name='User name')),
                ('first_name', models.CharField(max_length=64, verbose_name='Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Surname')),
                ('birth_day', models.PositiveSmallIntegerField()),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='Email')),
            ],
        ),
    ]
